# Generated by Django 4.1.1 on 2022-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_user_delete_developeruser_delete_manageruser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
